import { isCsharpFile } from "./isCsharpFile";

const GENERATED_SUFFIXES = [".g.cs", ".designer.cs"];
const BUILD_OUTPUT_DIR = /(^|[/\\])obj[/\\]/;
const AUTO_GENERATED_MARKER = "<auto-generated";
const HEADER_LINES = 10;

function hasAutoGeneratedHeader(content: string): boolean {
	return content
		.split("\n", HEADER_LINES)
		.some((line) => line.toLowerCase().includes(AUTO_GENERATED_MARKER));
}

export function isGeneratedCsharpFile(
	filePath: string | undefined,
	content?: string,
): boolean {
	if (!isCsharpFile(filePath) || !filePath) return false;
	const lower = filePath.toLowerCase();
	if (GENERATED_SUFFIXES.some((suffix) => lower.endsWith(suffix))) return true;
	if (BUILD_OUTPUT_DIR.test(lower)) return true;
	return content !== undefined && hasAutoGeneratedHeader(content);
}
