import { describe, expect, it } from "vitest";
import { isGeneratedCsharpFile } from "./isGeneratedCsharpFile";

describe("isGeneratedCsharpFile", () => {
	it("treats a .g.cs file as generated", () => {
		expect(isGeneratedCsharpFile("src/Api/Routes.g.cs")).toBe(true);
	});

	it("treats a .Designer.cs file as generated", () => {
		expect(isGeneratedCsharpFile("src/Forms/Main.Designer.cs")).toBe(true);
	});

	it("matches .designer.cs regardless of case", () => {
		expect(isGeneratedCsharpFile("src/Forms/Main.designer.cs")).toBe(true);
	});

	it("treats a file under obj/ as generated", () => {
		expect(isGeneratedCsharpFile("src/Api/obj/Debug/Api.AssemblyInfo.cs")).toBe(
			true,
		);
	});

	it("treats a file under a windows-separated obj path as generated", () => {
		expect(isGeneratedCsharpFile(String.raw`src\Api\obj\Program.cs`)).toBe(
			true,
		);
	});

	it("treats a repo-root obj path as generated", () => {
		expect(isGeneratedCsharpFile("obj/Program.cs")).toBe(true);
	});

	it("does not treat a directory merely containing obj as generated", () => {
		expect(isGeneratedCsharpFile("src/objects/Program.cs")).toBe(false);
	});

	it("treats content with an auto-generated header as generated", () => {
		const content = [
			"//---------------------------",
			"// <auto-generated>",
			"//   Tool output.",
			"// </auto-generated>",
			"//---------------------------",
			"var a = 1;",
		].join("\n");

		expect(isGeneratedCsharpFile("src/Program.cs", content)).toBe(true);
	});

	it("ignores an auto-generated marker below the header lines", () => {
		const content = [
			...Array.from({ length: 12 }, (_, i) => `var v${i} = ${i};`),
			"// <auto-generated>",
		].join("\n");

		expect(isGeneratedCsharpFile("src/Program.cs", content)).toBe(false);
	});

	it("does not treat a hand-written .cs file as generated", () => {
		expect(isGeneratedCsharpFile("src/Program.cs", "var a = 1;")).toBe(false);
	});

	it("does not treat a non-csharp file as generated", () => {
		expect(isGeneratedCsharpFile("src/api/obj/index.ts")).toBe(false);
	});

	it("handles a missing file path", () => {
		expect(isGeneratedCsharpFile(undefined)).toBe(false);
	});
});
