import type { Session, SessionInfo } from "./createSession";
import { originForCwd } from "./originForCwd";
import { repoGroupForCwd } from "./repoGroupForCwd";

export function toSessionInfo({
	id,
	name,
	title,
	generatedTitle,
	subtitle,
	commandType,
	harness,
	status,
	startedAt,
	runningMs,
	runningSince,
	runName,
	runArgs,
	server,
	serverPort,
	serverOrigin,
	assistArgs,
	cwd,
	claudeSessionId,
	restored,
	error,
	activity,
	autoRun,
	autoAdvance,
	starred,
	usedPct,
	design,
	pendingPrPreview,
	undurable,
	closing,
}: Session): SessionInfo {
	return {
		id,
		name,
		title,
		generatedTitle,
		subtitle,
		commandType,
		harness,
		status,
		startedAt,
		runningMs,
		runningSince,
		runName,
		runArgs,
		server,
		port: serverPort,
		remoteOrigin: serverOrigin ?? originForCwd(cwd),
		assistArgs,
		cwd,
		claudeSessionId,
		repoGroup: repoGroupForCwd(cwd),
		restored,
		error,
		activity,
		autoRun,
		autoAdvance,
		starred,
		usedPct,
		design,
		pendingPrPreview,
		undurable,
		closing,
	};
}
